# Generated by Django 3.2.7 on 2021-10-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='email',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
