# Generated by Django 3.2.7 on 2021-10-07 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ente',
            fields=[
                ('ente_id', models.CharField(max_length=650, primary_key=True, serialize=False)),
                ('ente_name', models.CharField(max_length=1500)),
            ],
            options={
                'verbose_name_plural': 'Enti',
            },
        ),
        migrations.CreateModel(
            name='Ruolo',
            fields=[
                ('ruolo_id', models.CharField(max_length=650, primary_key=True, serialize=False)),
                ('ruolo_name', models.CharField(max_length=1500)),
            ],
            options={
                'verbose_name_plural': 'Ruoli',
            },
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('surname', models.CharField(max_length=1000)),
                ('hash_pass', models.CharField(max_length=1650)),
                ('ente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ente', to='Utente.ente')),
                ('ruolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruolo', to='Utente.ruolo')),
            ],
            options={
                'verbose_name_plural': 'Utenti',
            },
        ),
    ]
