upstream django {
  server django:8000;
}

server {
    listen 8000;
    server_name localhost;

    client_max_body_size 10G;

    location /getAllNodes {
        proxy_pass http://django;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    # Serve il frontend Angular (build statica)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Serve le API di Django
    location /api {
        proxy_pass http://django;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /dataset {
        proxy_pass http://django;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Serve eventuali file statici Django
    location /static/ {
        alias /static/;
        autoindex on;
    }

    proxy_read_timeout 99999;
    proxy_connect_timeout 99999;
    proxy_send_timeout 99999;
}