version: "3.9"

services:
  django:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./code:/code
    command: >
      sh -c "python AdriaProject/manage.py makemigrations && python AdriaProject/manage.py migrate && cd AdriaProject && hypercorn --bind '0.0.0.0:8000' AdriaProject.asgi:application --reload "
    environment:
      - DB_HOST=db
      - DB_NAME=$POSTGRES_NAME
      - DB_USER=$POSTGRES_USER
      - DB_PASS=$POSTGRES_PASSWORD
    depends_on:
      - db
  # angular:
  #   build: code/angular-front/adria-project-front
  #   ports:
  #     - "4200:4200"
  #   depends_on:
  #     - django
  db:
    image: postgres:13
    ports:
      - "5433:5433"
      - "5532:5432"
    environment:
      - POSTGRES_DB=$POSTGRES_NAME
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
    - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume: