FROM node:18.15.0 as build

# WORKDIR /usr/src/app
# COPY code/adria_project_frontend/package*.json ./
# RUN npm install
# COPY code/adria_project_frontend/. .
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .

# Build Angular app in production mode (usa environment.prod.ts)
RUN npm run build -- --configuration production

# ----
# Second stage: serve with nginx
FROM nginx:1.21-alpine

# Copia i file buildati Angular nella root HTML di Nginx
COPY --from=build /usr/src/app/dist/adria-project-front /usr/share/nginx/html

# Usa la configurazione prod di Nginx
COPY nginx.prod.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
