FROM node:19.6

# #Create a directory where our app will be placed
# RUN mkdir -p /usr/src/app
# # RUN mkdir -p '/app'

# # Change directory so that our commands run inside this new directory
# WORKDIR /usr/src/app
# # WORKDIR '/app'

# # Copy dependency definitions
# COPY package.json /usr/src/app
# # COPY package.json /app

# # Install dependecies
# #Possiamo provare questo anche
# #RUN npm install -g @angular/cli

# RUN npm install

# # # Generate the build of the application
# # RUN npm run build # probabilmente non serve

# # Get all the code needed to run the app
# COPY . /usr/src/app
# # COPY . /app

# RUN chmod 777 /usr/src/app/node_modules/.bin/ng
# # RUN chmod 777 /app/node_modules/.bin/ng

# RUN chmod 777 /usr/src/app/node_modules/.bin/ng.cmd
# # RUN chmod 777 /app/node_modules/.bin/ng.cmd

# # Expose the port the app runs in
# EXPOSE 4200
# # EXPOSE 80

# # Serve the app
# CMD ["npm", "start"]
